#pragma once

// Warning: This file is autogenerated from config.py, do not edit it!

#define CAMERA_WIDTH 1280
#define CAMERA_HEIGHT 720
#define CAMERA_FPS 15
#define LOG_DURATION_SECONDS 60
#define LOG_PATH "/media/card"
#define LOG_SERVICE "http://jake-training-box.jakepoz.gmail.com.beta.tailscale.net:8000"
#define MODEL_STORAGE_PATH "/home/robot/models"
#define MODEL_SERVICE "http://jake-training-box.jakepoz.gmail.com.beta.tailscale.net:8000"
#define ENCODER_QP 10
#define ENCODER_DEV "/dev/nvhost-msenc"
#define ENCODER_COMP_NAME "NVENC"
#define AUDIO_DEVICE_NAME "hw:APE,0"
#define AUDIO_PCM_FORMAT "S32_LE"
#define AUDIO_SAMPLE_RATE 48000
#define AUDIO_CHANNELS 2
#define ODRIVE_SERIAL_PORT "/dev/ttyACM0"
#define ODRIVE_BAUD_RATE 115200
#define ODRIVE_MAX_SPEED 2.000000000000f
#define SIMPLEBGC_SERIAL_PORT "/dev/ttyTHS0"
#define SIMPLEBGC_BAUD_RATE 115200
