env = Environment(CPPPATH=[".", 
                            "/usr/src/jetson_multimedia_api/include",
                            "/usr/src/jetson_multimedia_api/include/libjpeg-8b",
                            "/usr/include/libdrm"],
                  LIBPATH = ["/usr/lib", "/usr/local/lib", "/usr/lib/aarch64-linux-gnu/tegra/"])

jetson_multimedia_lib = env.Library("multimedia_api", Glob("*.cpp"), LIBS=["pthread", "drm"])
Export("jetson_multimedia_lib")
