Import("jetson_multimedia_lib")

env = Environment(CPPPATH=[".", "/usr/src/jetson_multimedia_api/include"],
                  LIBPATH = ["/usr/lib", "/usr/local/lib", "/usr/lib/aarch64-linux-gnu/tegra/"],)

env.Program("hello", ["hello.cpp"], LIBS=["realsense2", jetson_multimedia_lib, "nvbuf_utils", "v4l2", "pthread"])
env.Program("nvencoder", ["nvencoder.cpp"], LIBS=["realsense2", "nvbuf_utils", "v4l2", "pthread"])

